it_blaster_routing:
    resource: "@ItBlasterMainBundle/Resources/config/routing/all.yml"
    prefix:   /

ck_finder:
    resource: "@JonlilCKFinderBundle/Resources/config/routing/routing.yml"
    prefix: /ckfinder

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /cms

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /cms