#Основной роутинг
it_blaster_main:
    resource: "main.yml"

#Проекты пользователя
it_blaster_projects:
    resource: "projects.yml"

#Ссылки проекта
it_blaster_project_links:
    resource: "project_links.yml"

#Отчёты
it_blaster_reports:
    resource: "reports.yml"