parameters:
  project.class:  ItBlaster\MainBundle\Form\ProjectType

services:
    #Форма добавления нового проекта
    it_blaster_main.type.project:
        class: %project.class%
        tags:
            - {name: form.type, alias: project }