parameters:
  project.class:  ItBlaster\MainBundle\Form\ProjectType
  project_link.class:  ItBlaster\MainBundle\Form\ProjectLinkType

services:

    #Форма добавления нового проекта
    it_blaster_main.type.project:
        class: %project.class%
        tags:
            - {name: form.type, alias: project }

    #Форма добавления ссылки проекта
    it_blaster_main.type.project_link:
        class: %project_link.class%
        tags:
            - {name: form.type, alias: project_link }