parameters:
    project_service.class:  ItBlaster\MainBundle\Service\ProjectService
    check_service.class:    ItBlaster\MainBundle\Service\CheckService
    mail_service.class:     ItBlaster\MainBundle\Service\MailService

services:

#Сервис для работы с проектами
    project_service:
        class:      %project_service.class%
        arguments:  [@request_stack]

#Сервис проверки доступности ссылок
    check_service:
        class:      %check_service.class%

    mail_service:
        class:      %mail_service.class%
        arguments:  [@mailer, %mailer_user%, %mailer_user_title%, @templating]